modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dualtintblocks"
version="${file.jarVersion}"
displayName="Dual Tint Blocks"
authors="sciwhiz12"
description='''
Example mod for dual tinted blocks
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
